package containerconf

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/amadeusitgroup/cds/internal/cenv"
	cg "github.com/amadeusitgroup/cds/internal/global"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func isolateDefaultArtifactHome(t *testing.T) string {
	t.Helper()

	homeDir := t.TempDir()
	t.Setenv("HOME", homeDir)
	t.Setenv("CDS_CONFIG_PATH", homeDir)
	t.Setenv(registryAuthFileEnv, "")
	return homeDir
}

func TestCollectArtifactsReturnsDockerfileSourceAndIdentifier(t *testing.T) {
	isolateDefaultArtifactHome(t)
	configDir := filepath.Join(t.TempDir(), ".devcontainer")
	config := NewConfig()
	config.Set(KBuild+"."+KBuildDockerfile, "Dockerfile")

	artifacts, err := CollectArtifacts(config, configDir)
	require.NoError(t, err)
	require.Len(t, artifacts, 1)
	identifier, err := DockerfileIdentifier(config)
	require.NoError(t, err)

	assert.Equal(t, RequiredArtifact{
		Identifier: identifier,
		Source: SourceRef{
			Type: SourceTypeLocalFS,
			Ref:  filepath.Join(configDir, "Dockerfile"),
		},
	}, artifacts[0])
}

func TestCollectArtifactsResolvesPathOutsideConfigDir(t *testing.T) {
	isolateDefaultArtifactHome(t)
	projectDir := t.TempDir()
	configDir := filepath.Join(projectDir, ".devcontainer")
	config := NewConfig()
	config.Set(KBuild+"."+KBuildDockerfile, "../Dockerfile")

	artifacts, err := CollectArtifacts(config, configDir)
	require.NoError(t, err)
	require.Len(t, artifacts, 1)
	identifier, err := DockerfileIdentifier(config)
	require.NoError(t, err)

	assert.Equal(t, identifier, artifacts[0].Identifier)
	assert.Equal(t, "resource/dockerfile/Dockerfile", identifier)
	assert.Equal(t, SourceRef{
		Type: SourceTypeLocalFS,
		Ref:  filepath.Join(projectDir, "Dockerfile"),
	}, artifacts[0].Source)
}

func TestCollectArtifactsReturnsDefaultAuthFileWhenPresent(t *testing.T) {
	isolateDefaultArtifactHome(t)
	authFilePath := cenv.ConfigFile(cg.KContainerAuthFileName)
	require.NoError(t, os.MkdirAll(filepath.Dir(authFilePath), 0700))
	require.NoError(t, os.WriteFile(authFilePath, []byte(`{"auths":{}}`), 0600))
	config := NewConfig()
	config.Set(KImage, "dockerhub.rnd.fix.me/dummy/image:0.1.0")

	artifacts, err := CollectArtifacts(config, t.TempDir())
	require.NoError(t, err)
	require.Len(t, artifacts, 1)
	identifier, err := SingletonIdentifier(KindAuthFile)
	require.NoError(t, err)

	assert.Equal(t, RequiredArtifact{
		Identifier: identifier,
		Source: SourceRef{
			Type: SourceTypeLocalFS,
			Ref:  authFilePath,
		},
	}, artifacts[0])
}

func TestCollectArtifactsUsesRegistryAuthFileOverride(t *testing.T) {
	isolateDefaultArtifactHome(t)
	authFilePath := filepath.Join(t.TempDir(), "auth.json")
	require.NoError(t, os.WriteFile(authFilePath, []byte(`{"auths":{}}`), 0600))
	t.Setenv(registryAuthFileEnv, authFilePath)
	config := NewConfig()
	config.Set(KImage, "dockerhub.rnd.fix.me/dummy/image:0.1.0")

	artifacts, err := CollectArtifacts(config, t.TempDir())
	require.NoError(t, err)
	require.Len(t, artifacts, 1)

	assert.Equal(t, SourceRef{
		Type: SourceTypeLocalFS,
		Ref:  authFilePath,
	}, artifacts[0].Source)
}

func TestCollectArtifactsRejectsMissingRegistryAuthFileOverride(t *testing.T) {
	isolateDefaultArtifactHome(t)
	t.Setenv(registryAuthFileEnv, filepath.Join(t.TempDir(), "missing-auth.json"))
	config := NewConfig()
	config.Set(KImage, "dockerhub.rnd.fix.me/dummy/image:0.1.0")

	_, err := CollectArtifacts(config, t.TempDir())
	require.Error(t, err)
	assert.Contains(t, err.Error(), KindAuthFile+":")
	assert.Contains(t, err.Error(), "does not exist")
}

func TestCollectArtifactsGeneratesAuthorizedKeysFromDefaultPublicKey(t *testing.T) {
	homeDir := isolateDefaultArtifactHome(t)
	publicKeyPath := filepath.Join(homeDir, ".ssh", "id_rsa.pub")
	require.NoError(t, os.MkdirAll(filepath.Dir(publicKeyPath), 0700))
	require.NoError(t, os.WriteFile(publicKeyPath, []byte("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICds generated by test\n\n"), 0600))
	config := NewConfig()
	config.Set(KImage, "dockerhub.rnd.fix.me/dummy/image:0.1.0")

	artifacts, err := CollectArtifacts(config, t.TempDir())
	require.NoError(t, err)
	require.Len(t, artifacts, 1)
	identifier, err := SingletonIdentifier(KindPubKey)
	require.NoError(t, err)

	assert.Equal(t, RequiredArtifact{
		Identifier: identifier,
		Source: SourceRef{
			Type: SourceTypeInline,
			Ref:  "authorized_keys",
			Data: []byte("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICds generated by test\n"),
		},
	}, artifacts[0])
}

func TestCollectArtifactsFallsBackToEd25519PublicKey(t *testing.T) {
	homeDir := isolateDefaultArtifactHome(t)
	publicKeyPath := filepath.Join(homeDir, ".ssh", "id_ed25519.pub")
	require.NoError(t, os.MkdirAll(filepath.Dir(publicKeyPath), 0700))
	require.NoError(t, os.WriteFile(publicKeyPath, []byte("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEd25519\n"), 0600))
	config := NewConfig()
	config.Set(KImage, "dockerhub.rnd.fix.me/dummy/image:0.1.0")

	artifacts, err := CollectArtifacts(config, t.TempDir())
	require.NoError(t, err)
	require.Len(t, artifacts, 1)

	assert.Equal(t, SourceRef{
		Type: SourceTypeInline,
		Ref:  "authorized_keys",
		Data: []byte("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEd25519\n"),
	}, artifacts[0].Source)
}

func TestCollectArtifactsReturnsEmptyWithoutConfigDerivedFiles(t *testing.T) {
	isolateDefaultArtifactHome(t)
	config := NewConfig()
	config.Set(KImage, "dockerhub.rnd.fix.me/dummy/image:0.1.0")

	artifacts, err := CollectArtifacts(config, t.TempDir())
	require.NoError(t, err)
	assert.Empty(t, artifacts)
}

func TestCollectArtifactsRejectsRelativePathWithoutConfigDir(t *testing.T) {
	isolateDefaultArtifactHome(t)
	config := NewConfig()
	config.Set(KBuild+"."+KBuildDockerfile, "Dockerfile")

	_, err := CollectArtifacts(config, "")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "config directory is required")
}
