syntax = "proto3";

package api.v1.artifact;
option go_package = "github.com/amadeusitgroup/cds/cdspb";

import "internal/api/v1/artifact/artifact_descriptor.proto";

// PrepareArtifactsRequest advertises all artifacts required by the next deploy.
message PrepareArtifactsRequest {
    // descriptors are the artifacts found during configuration analysis.
    repeated ArtifactDescriptor descriptors = 1;

    // project_name scopes artifacts to one project staging area.
    string project_name = 2;
}
