package shexec

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"testing"

	"github.com/amadeusitgroup/cds/internal/cerr"
	"github.com/amadeusitgroup/cds/internal/cos"
	cg "github.com/amadeusitgroup/cds/internal/global"
	"github.com/stretchr/testify/assert"
)

type mockedTarget struct {
	name      string
	pathToPrv string
	pathToPub string
}

func (mt mockedTarget) FQDN() string {
	return mt.name
}

func (mt mockedTarget) HasPassword() bool {
	return false
}

func (mt mockedTarget) Password() string {
	return cg.EmptyStr
}

func (mt mockedTarget) PathToPrv() string {
	return mt.pathToPrv
}

func (mt mockedTarget) PathToPub() string {
	return mt.pathToPub
}

func (mt mockedTarget) Port() int {
	return 0
}

func (mt mockedTarget) Username() string {
	return cg.EmptyStr
}

func TestAddComment(t *testing.T) {
	pubKeyBase := "ecdsa-sha2-nistp384 AAEEEDDD"
	myPubKeyBytes := []byte(pubKeyBase + "\n")
	result, err := addCdsWatermarkToPublicKey(myPubKeyBytes)
	if err != nil {
		t.Fatalf("Test failed because of %v", err)
	}
	resultStr := string(result)

	// Works for username@hostname and for AMAIISDOM\username@hostname
	regexpStr := pubKeyBase + " generated by CDS: (\\w|\\\\)+@\\w+\\n"
	r, _ := regexp.Compile(regexpStr)
	if !r.MatchString(resultStr) {
		t.Fatalf("%v was supposed to match %v", resultStr, regexpStr)
	}
}

func TestCheckValidSSHKeyPairExistence(t *testing.T) {
	cos.SetMockedFileSystem()
	defer cos.SetRealFileSystem()

	currentWorkDir, err := getCurrentWorkingDir()
	if err != nil {
		t.Fatal(err)
	}
	mockedPublicKeyPath := filepath.Join(currentWorkDir, "mockedPublicKey")
	mockedPrivateKeyPath := filepath.Join(currentWorkDir, "mockedPrivateKey")

	h := mockedTarget{name: "mockedHost", pathToPub: mockedPublicKeyPath, pathToPrv: mockedPrivateKeyPath}

	expectedError := cerr.NewError(fmt.Sprintf("Host %s does not have a valid ssh key pair", h.FQDN()))
	// Both private and public ssh keys are missing
	assert.Error(t, CheckValidSSHKeyPairExistence(h))
	assert.Equal(t, cerr.Message(CheckValidSSHKeyPairExistence(h)), cerr.Message(expectedError))

	// Missing private ssh key
	if _, err := cos.Fs.OpenFile(mockedPublicKeyPath, os.O_CREATE|os.O_RDWR, fs.FileMode(0600)); err != nil {
		t.Fatal(err)
	}
	assert.Error(t, CheckValidSSHKeyPairExistence(h))
	assert.Equal(t, cerr.Message(CheckValidSSHKeyPairExistence(h)), cerr.Message(expectedError))

	if err := cos.Fs.Remove(mockedPublicKeyPath); err != nil {
		t.Fatal(err)
	}

	// Missing public ssh key
	if _, err := cos.Fs.OpenFile(mockedPrivateKeyPath, os.O_CREATE|os.O_RDWR, fs.FileMode(0600)); err != nil {
		t.Fatal(err)
	}
	assert.Error(t, CheckValidSSHKeyPairExistence(h))
	assert.Equal(t, cerr.Message(CheckValidSSHKeyPairExistence(h)), cerr.Message(expectedError))

	//Both keys are present
	if _, err := cos.Fs.OpenFile(mockedPublicKeyPath, os.O_CREATE|os.O_RDWR, fs.FileMode(0600)); err != nil {
		t.Fatal(err)
	}
	assert.NoError(t, CheckValidSSHKeyPairExistence(h))
	assert.Equal(t, CheckValidSSHKeyPairExistence(h), nil)
}
