package shexec

import (
	"bufio"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"io/fs"
	"net"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/knownhosts"

	"github.com/amadeusitgroup/cds/internal/cerr"
	"github.com/amadeusitgroup/cds/internal/clog"
	"github.com/amadeusitgroup/cds/internal/cos"
)

var (
	secret          = ""
	secretValidated = false
	passwordTries   = 0
)

const (
	maxPasswordTries = 3
)

var (
	alreadyCheckKnownHosts = false
)

// This adds additional info about where cds was started and by who
func addCdsWatermarkToPublicKey(publicBytes []byte) ([]byte, error) {
	user, errUser := user.Current()
	if errUser != nil {
		return nil, errUser
	}
	hostname, errHostame := os.Hostname()
	if errHostame != nil {
		return nil, errHostame
	}

	// as there is a newline char(s) (yay platform implementations \r\n or \n)
	// we remove those to have our comment on the same line
	publicBytes = []byte(strings.TrimRight(string(publicBytes), "\r\n"))
	// we rely on the go fmt.Sprintf to know which newline to use :)
	suffixBytes := []byte(fmt.Sprintf(" generated by CDS: %v@%v\n", user.Username, hostname))
	publicBytes = append(publicBytes, suffixBytes...)

	return publicBytes, nil
}

type KeyPair struct {
	PathToPub string
	PathToPrv string
}

// generate a ssh key pair using the given suffix,
// will result in the creation of $HOME/.ssh/id_rsa_SUFFIX key pair
func GenerateKeyPair(suffix string) (KeyPair, error) {
	// generate key pair using ecdsa-sha2-nistp384 algo
	privateKey, _ := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	publicKey := &privateKey.PublicKey
	// encode Private Key using PEM (SSH2 format)
	privateBytes := encodeECDSAPrivateKey(privateKey)
	// encode Puplic Key using OpenSSH format
	pub, _ := ssh.NewPublicKey(publicKey)
	publicBytes := ssh.MarshalAuthorizedKey(pub)
	// write keys to destination files $HOME/.ssh
	privateKeyFile := fmt.Sprintf("./id_rsa_%v", suffix)
	publicKeyFile := fmt.Sprintf("./id_rsa_%v.pub", suffix)
	keyPairPath := KeyPair{
		PathToPub: filepath.Join(getUserHomeDir(), ".ssh", publicKeyFile),
		PathToPrv: filepath.Join(getUserHomeDir(), ".ssh", privateKeyFile),
	}
	if err := writeKeyTofile(privateBytes, keyPairPath.PathToPrv); err != nil {
		return KeyPair{}, cerr.AppendError(fmt.Sprintf("Failed to write private key to file (%s)", keyPairPath.PathToPrv), err)
	}

	// add user and hostname where cds was launched to give context
	if newPub, err := addCdsWatermarkToPublicKey(publicBytes); err == nil {
		publicBytes = newPub
	}

	if err := writeKeyTofile(publicBytes, keyPairPath.PathToPub); err != nil {
		return KeyPair{}, cerr.AppendError(fmt.Sprintf("Failed to write public key to file (%s)", keyPairPath.PathToPub), err)
	}
	return keyPairPath, nil
}

// Generate public key from private key specified in pathToPrv.
// Support only keys generated using ECDSA or ED25519 algorithms.
func GeneratePublicKey(pathToPrv string) (string, error) {
	pathToPubKeyFile := fmt.Sprintf("%v.pub", pathToPrv)
	if cos.Exists(pathToPubKeyFile) {
		clog.Debug(fmt.Sprintf("Public key file '%s' exists. Use it!", pathToPubKeyFile))
		return pathToPubKeyFile, nil
	}
	pem, readErr := cos.ReadFile(pathToPrv)
	if readErr != nil {
		return "", cerr.AppendError(fmt.Sprintf("Failed to read private key from file (%s)", pathToPrv), readErr)
	}
	privateKey, parseErr := ssh.ParseRawPrivateKey(pem)
	if parseErr != nil {
		return "", cerr.AppendError(fmt.Sprintf("Failed to parse private key in file (%s)", pathToPrv), parseErr)
	}

	var publicKey ssh.PublicKey
	var errNewKey error
	switch key := privateKey.(type) {
	case *ecdsa.PrivateKey:
		publicKey, errNewKey = ssh.NewPublicKey(&key.PublicKey)
	case *ed25519.PrivateKey:
		pkey_ed25519, _ := key.Public().(ed25519.PublicKey)
		publicKey, errNewKey = ssh.NewPublicKey(pkey_ed25519)
	default:
		return "", cerr.NewError(`Supports ecdsa/ed25519 algorithm. Use for example: "ssh-keygen -t ecdsa -b <256, 384 or 521>"`)
	}

	if errNewKey != nil {
		return "", cerr.AppendError("Failed to generate new public key", errNewKey)
	}

	publicBytes := ssh.MarshalAuthorizedKey(publicKey)

	// add user and hostname where cds was launched to give context
	if newPub, err := addCdsWatermarkToPublicKey(publicBytes); err == nil {
		publicBytes = newPub
	}

	if err := writeKeyTofile(publicBytes, pathToPubKeyFile); err != nil {
		return "", cerr.AppendError(fmt.Sprintf("Failed to write public key to file (%s)", pathToPubKeyFile), err)
	}
	return pathToPubKeyFile, nil
}

func getHostKey(host string) (ssh.PublicKey, error) {
	knownhostFilePath := filepath.Join(getUserHomeDir(), ".ssh", "known_hosts")
	if cos.NotExist(knownhostFilePath) {
		return nil, cerr.NewError("Failed to get host key, known_hosts does't not exist!")
	}

	file, err := cos.Fs.Open(filepath.Join(getUserHomeDir(), ".ssh", "known_hosts"))
	if err != nil {
		return nil, cerr.AppendError("Failed to open known_hosts file", err)
	}
	defer func() {
		_ = file.Close()
	}()

	scanner := bufio.NewScanner(file)
	var hostKey ssh.PublicKey
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), " ")
		if len(fields) != 3 {
			continue
		}
		// use HasPrefix to filter out "[HOSTNAME]:PORT ... " entries
		// TODO:FixMe: proper regex
		if strings.HasPrefix(fields[0], host) {
			var err error
			hostKey, _, _, _, err = ssh.ParseAuthorizedKey(scanner.Bytes())
			if err != nil {
				return nil, cerr.AppendError(fmt.Sprintf("Error parsing %q", fields[2]), err)
			}
		}
	}

	if hostKey == nil {
		return nil, cerr.NewError(fmt.Sprintf("No host key available for %s", host))
	}
	return hostKey, nil
}

func encodeECDSAPrivateKey(pkey *ecdsa.PrivateKey) []byte {
	x509Encoded, err := x509.MarshalECPrivateKey(pkey)
	if err != nil {
		clog.Error("Failed to Marshal key")
		return []byte{}
	}
	pemEncoded := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: x509Encoded})
	return pemEncoded
}

func writeKeyTofile(key []byte, path string) error {
	if err := cos.WriteFile(path, key, 0600); err != nil {
		return cerr.AppendError(fmt.Sprintf("Failed to write key to file (%s)", path), err)
	}
	return nil
}

func provideHostKeyCallback() ssh.HostKeyCallback {
	return func(hostname string, remote net.Addr, pubkey ssh.PublicKey) error {

		// however this function runs, just do it once with the
		// alreadyCheckKnownHosts variable
		if alreadyCheckKnownHosts {
			clog.Debug("Already checked known_hosts. Nothing to do.")
			return nil
		}
		defer func() {
			alreadyCheckKnownHosts = true
		}()

		knownHostFilePath := filepath.Join(getUserHomeDir(), ".ssh", "known_hosts")
		if cos.NotExist(knownHostFilePath) {
			clog.Warn("Missing known_hosts file.")
			clog.Warn("Insecure host key verification is triggered.")
			return nil
		}

		hostKey, _ := getHostKey(hostname)
		if err := ssh.FixedHostKey(hostKey)(hostname, remote, pubkey); err == nil {
			clog.Warn("Insecure host key verification is triggered although host key is present")
			return nil
		}

		host := knownhosts.Normalize(remote.String())
		hostkeyEntry := knownhosts.Line([]string{hostname, host}, pubkey)

		// checking if we already registered that host previously in known_hosts file
		readFile, err := cos.Fs.OpenFile(knownHostFilePath, os.O_RDONLY, fs.FileMode(0700))
		if err != nil {
			clog.Warn("Failed to open known_hosts file", err)
			clog.Warn("Insecure host key verification is triggered.")
			return nil
		}

		fileScanner := bufio.NewScanner(readFile)
		fileScanner.Split(bufio.ScanLines)

		for fileScanner.Scan() {
			line := fileScanner.Text()
			if strings.Contains(line, hostkeyEntry) {
				clog.Debug(fmt.Sprintf("Host %s alredy registered in known_hosts with correct key", hostname))
				_ = readFile.Close()
				// nothing do do, exit :)
				return nil
			}
		}
		_ = readFile.Close()

		// at this point the known_hosts file exist but does not contain our line
		file, err := cos.Fs.OpenFile(knownHostFilePath, os.O_WRONLY|os.O_APPEND, fs.FileMode(0700))
		if err != nil {
			clog.Warn("Failed to open known_hosts file", err)
			clog.Warn("Insecure host key verification is triggered.")
			return nil
		}
		defer func() {
			_ = file.Close()
		}()

		clog.Info(fmt.Sprintf("Registering host %s in the known_hosts file", hostname))
		_, err = fmt.Fprintln(file, hostkeyEntry, " generated by CDS")
		if err != nil {
			return cerr.AppendError(fmt.Sprintf("Failed to write hostkey to known_hosts file (%s)", knownHostFilePath), err)
		}

		return nil
	}
}

func CheckValidSSHKeyPairExistence(host target) error {
	if cos.NotExist(host.PathToPub()) {
		clog.Warn(fmt.Sprintf("Key %s is missing", host.PathToPub()))
		return cerr.NewError(fmt.Sprintf("Host %s does not have a valid ssh key pair", host.FQDN()))
	}
	if cos.NotExist(host.PathToPrv()) {
		clog.Warn(fmt.Sprintf("Key %s is missing", host.PathToPrv()))
		return cerr.NewError(fmt.Sprintf("Host %s does not have a valid ssh key pair", host.FQDN()))
	}
	return nil
}
